site_name: inha-rby1-dataset
repo_url: https://github.com/inha-united-athome/inha-rby1-dataset
site_url: https://inha-united-athome.github.io/inha-rby1-dataset/

theme:
    name: material
    palette:
        scheme: default
        primary: blue
        accent: cyan
    front:
        text: Roboto
        code: Roboto Mono

markdown_extensions:
  - meta
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2026 Inha-United
extra:
    social:
        - icon: material/home
          link: https://inha-united.github.io/Home2026/
        - icon: fontawesome/brands/github
          link: https://github.com/inha-united-athome/inha-rby1-dataset

extra_css:
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

nav:
    - 'index.md'